const topPicksTransformationsData = [
  {
    img: `/images/top-picks-transformations/${1}.jpg`,
    name: 'Kamal Nimr',
    beforeWeight: 77.5,
    afterWeight: 79,
    beforeBodyFat: 15,
    afterBodyFat: 10,
  },
  {
    img: `/images/top-picks-transformations/${2}.jpg`,
    name: 'Nashaat Mohamed',
    beforeWeight: 76,
    afterWeight: 65,
    beforeBodyFat: 19.9,
    afterBodyFat: 6.7,
  },
  {
    img: `/images/top-picks-transformations/${3}.jpg`,
    name: 'Ahmed attalah',
    beforeWeight: 75,
    afterWeight: 81,
    beforeBodyFat: 10,
    afterBodyFat: 8,
  },
  {
    img: `/images/top-picks-transformations/${4}.jpg`,
    name: 'Ahmed Sabry',
    beforeWeight: 78,
    afterWeight: 71,
    beforeBodyFat: 25,
    afterBodyFat: 12,
  },
  {
    img: `/images/top-picks-transformations/${5}.jpg`,
    name: 'Hussein Ali',
    beforeWeight: 88.1,
    afterWeight: 73.5,
    beforeBodyFat: 25.2,
    afterBodyFat: 9,
  },
  {
    img: `/images/top-picks-transformations/${6}.jpg`,
    name: 'Abdullah bughdadi',
    beforeWeight: 81.5,
    afterWeight: 74,
    beforeBodyFat: 20.1,
    afterBodyFat: 11.1,
  },
  {
    img: `/images/top-picks-transformations/${7}.jpg`,
    name: 'Mohamed Hemida',
    beforeWeight: 108,
    afterWeight: 85,
    beforeBodyFat: 24.6,
    afterBodyFat: 12.5,
  },
  {
    img: `/images/top-picks-transformations/${8}.jpg`,
    name: 'Ahmed Sayed',
    beforeWeight: 135,
    afterWeight: 89,
    beforeBodyFat: 48,
    afterBodyFat: 12,
  },
  {
    img: `/images/top-picks-transformations/${9}.jpg`,
    name: 'mostafa ezzat',
    beforeWeight: 61,
    afterWeight: 62,
    beforeBodyFat: 15,
    afterBodyFat: 7,
  },
  {
    img: `/images/top-picks-transformations/${10}.jpg`,
    name: 'Abdullah Emara',
    beforeWeight: 71.5,
    afterWeight: 70,
    beforeBodyFat: 21.1,
    afterBodyFat: 13,
  },
  {
    img: `/images/top-picks-transformations/${11}.jpg`,
    name: 'Mohamed Mostafa',
    beforeWeight: 74,
    afterWeight: 82.5,
    beforeBodyFat: 14.8,
    afterBodyFat: 12,
  },
];

export default topPicksTransformationsData;
